### ISSUE TITLE
Still overflowing GPU VRAM with reduced batch size

### ISSUE THREAD

**Issue by Chadkowski** [himashi92/VT-UNet#27]
Hi! I'm still having issues with overflowing my VRAM (RTX 3090 24GB) whenever attempting to train. Even after I've redued my batch size to 1. Any ideas on what I can do?

**Comment by Chadkowski** [comment]
are you not supposed to be able to train base + small at same time with 24GB GPU?

**Comment by Chadkowski** [comment]
even when running base alone and small alone still overflow. I changed channels to 1 instead of 4 in Swin3D but to no avail

**Comment by himashi92** [comment]
Hi, you cannot load both models at once for training. Can you check whether any pids are listed under your GPU? Try this command : sudo fuser -v /dev/nvidia0

**Comment by himashi92** [comment]
What is the dataset you are trying to train here? If its brats, then input channel size is 4.

**Comment by Chadkowski** [comment]
I'm trying to train the Synapse dataset, Brats dataset worked fine to train both. When trying to train synapse it was giving me error that it expects 4 channels but only receives one so I changed input channels to 1.

I get the following error:
    (concat_back_dim): ModuleList(
      (0): Identity()
      (1): Linear(in_features=576, out_features=288, bias=False)
      (2): Linear(in_features=288, out_features=144, bias=False)
      (3): Linear(in_features=144, out_features=72, bias=False)
    )
    (norm): LayerNorm((576,), eps=1e-05, elementwise_affine=True)
    (norm_up): LayerNorm((72,), eps=1e-05, elementwise_affine=True)
    (up): FinalPatchExpand_X4(
      (expand): Linear(in_features=72, out_features=4608, bias=False)
      (norm): LayerNorm((72,), eps=1e-05, elementwise_affine=True)
    )
    (output): Conv3d(72, 4, kernel_size=(1, 1, 1), stride=(1, 1, 1), bias=False)
  )
)
2022-07-22 09:00:21.071064: 

2022-07-22 09:00:21.071555: 
epoch:  0
Traceback (most recent call last):
  File "/home/dawidr/.local/bin/vtunet_train", line 33, in <module>
    sys.exit(load_entry_point('vtunet', 'console_scripts', 'vtunet_train')())
  File "/home/VT-UNet/VTUNet/vtunet/run/run_training.py", line 150, in main
    trainer.run_training()
  File "/home/VT-UNet/VTUNet/vtunet/training/network_training/vtunetTrainerV2_vtunet_tumor_base.py", line 432, in run_training
    ret = super().run_training()
  File "/home/VT-UNet/VTUNet/vtunet/training/network_training/vtunetTrainer.py", line 319, in run_training
    super(vtunetTrainer, self).run_training()
  File "/home/VT-UNet/VTUNet/vtunet/training/network_training/network_trainer.py", line 459, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/VT-UNet/VTUNet/vtunet/training/network_training/vtunetTrainerV2_vtunet_tumor_base.py", line 229, in run_iteration
    output = self.network(data)
  File "/home/dawidr/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/VT-UNet/VTUNet/vtunet/network_architecture/vtunet_tumor.py", line 1128, in forward
    logits = self.swin_unet(x)
  File "/home/dawidr/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/VT-UNet/VTUNet/vtunet/network_architecture/vtunet_tumor.py", line 1089, in forward
    x = self.forward_up_features(x, x_downsample, v_values_1, k_values_1, q_values_1, v_values_2, k_values_2,
  File "/home/VT-UNet/VTUNet/vtunet/network_architecture/vtunet_tumor.py", line 957, in forward_up_features
    x = layer_up(x, v_values_1[3 - inx], k_values_1[3 - inx], q_values_1[3 - inx], v_values_2[3 - inx],
  File "/home/dawidr/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/VT-UNet/VTUNet/vtunet/network_architecture/vtunet_tumor.py", line 583, in forward
    x, _, _, _ = blk(x, attn_mask, prev_v2, prev_k2, prev_q2, True)
  File "/home/dawidr/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/VT-UNet/VTUNet/vtunet/network_architecture/vtunet_tumor.py", line 359, in forward
    x, x2, v, k, q = self.forward_part1(x, mask_matrix, prev_v, prev_k, prev_q, is_decoder)
  File "/home/VT-UNet/VTUNet/vtunet/network_architecture/vtunet_tumor.py", line 307, in forward_part1
    attn_windows, cross_attn_windows, v, k, q = self.attn(x_windows, mask=attn_mask, prev_v=prev_v, prev_k=prev_k,
  File "/home/dawidr/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/VT-UNet/VTUNet/vtunet/network_architecture/vtunet_tumor.py", line 197, in forward
    x2 = (attn2 @ prev_v).transpose(1, 2).reshape(B_, N, C)
RuntimeError: CUDA out of memory. Tried to allocate 244.00 MiB (GPU 0; 23.67 GiB total capacity; 20.23 GiB already allocated; 218.50 MiB free; 20.40 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dawidr/.local/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 102, in results_loop
    item = current_queue.get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/home/dawidr/.local/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 757, in answer_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
![Screenshot from 2022-07-22 09-00-34](https://user-images.githubusercontent.com/85929801/180382551-f092ad00-22c5-49c5-a24b-e5c677bdd666.png)

My configs in vtunet_tumor.py:
![image](https://user-images.githubusercontent.com/85929801/180382706-121ae7f3-a997-4550-b7fd-89bede5597ad.png)
![image](https://user-images.githubusercontent.com/85929801/180382762-bf889f2f-e933-4900-bd50-861b4533caa6.png)
and in default_configuration.py:
![image](https://user-images.githubusercontent.com/85929801/180382851-d810b80e-5232-4a62-b04d-cfcd4bc9ed87.png)

**Comment by Chadkowski** [comment]
actually, now the error is:

Traceback (most recent call last):
  File "/home/dawidr/.local/bin/vtunet_train", line 33, in <module>
    sys.exit(load_entry_point('vtunet', 'console_scripts', 'vtunet_train')())
  File "/home/VT-UNet/VTUNet/vtunet/run/run_training.py", line 150, in main
    trainer.run_training()
  File "/home/VT-UNet/VTUNet/vtunet/training/network_training/vtunetTrainerV2_vtunet_tumor_base.py", line 430, in run_training
    ret = super().run_training()
  File "/home/VT-UNet/VTUNet/vtunet/training/network_training/vtunetTrainer.py", line 319, in run_training
    super(vtunetTrainer, self).run_training()
  File "/home/VT-UNet/VTUNet/vtunet/training/network_training/network_trainer.py", line 459, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/VT-UNet/VTUNet/vtunet/training/network_training/vtunetTrainerV2_vtunet_tumor_base.py", line 229, in run_iteration
    output = self.network(data)
  File "/home/dawidr/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/VT-UNet/VTUNet/vtunet/network_architecture/vtunet_tumor.py", line 1128, in forward
    logits = self.swin_unet(x)
  File "/home/dawidr/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/VT-UNet/VTUNet/vtunet/network_architecture/vtunet_tumor.py", line 1089, in forward
    x = self.forward_up_features(x, x_downsample, v_values_1, k_values_1, q_values_1, v_values_2, k_values_2,
  File "/home/VT-UNet/VTUNet/vtunet/network_architecture/vtunet_tumor.py", line 947, in forward_up_features
    x = layer_up(x)
  File "/home/dawidr/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/VT-UNet/VTUNet/vtunet/network_architecture/vtunet_tumor.py", line 469, in forward
    x = x.view(B, D * 8, H, W, C)
RuntimeError: shape '[1, 32, 4, 4, 1152]' is invalid for input of size 294912

**Comment by Chadkowski** [comment]
Managed to sort it by changing patch size to 64/128/128 for my set but now I have the following issue..

2022-07-22 15:28:50.920116: 
epoch:  0
Traceback (most recent call last):
  File "/home/dawidr/.local/bin/vtunet_train", line 33, in <module>
    sys.exit(load_entry_point('vtunet', 'console_scripts', 'vtunet_train')())
  File "/home/VT-UNet/VTUNet/vtunet/run/run_training.py", line 150, in main
    trainer.run_training()
  File "/home/VT-UNet/VTUNet/vtunet/training/network_training/vtunetTrainerV2_vtunet_tumor_base.py", line 430, in run_training
    ret = super().run_training()
  File "/home/VT-UNet/VTUNet/vtunet/training/network_training/vtunetTrainer.py", line 319, in run_training
    super(vtunetTrainer, self).run_training()
  File "/home/VT-UNet/VTUNet/vtunet/training/network_training/network_trainer.py", line 459, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/VT-UNet/VTUNet/vtunet/training/network_training/vtunetTrainerV2_vtunet_tumor_base.py", line 232, in run_iteration
    l = self.loss(output, target)
  File "/home/dawidr/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/VT-UNet/VTUNet/vtunet/training/loss_functions/dice_loss.py", line 352, in forward
    ce_loss = self.ce(net_output, target[:, 0].long()) if self.weight_ce != 0 else 0
  File "/home/dawidr/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/VT-UNet/VTUNet/vtunet/training/loss_functions/crossentropy.py", line 12, in forward
    return super().forward(input, target.long())
  File "/home/dawidr/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1150, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/dawidr/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2846, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: Expected target size [1, 128, 128, 128], got [1, 64, 128, 128]

**Comment by himashi92** [comment]
Hi, the current version of VTUNet can only handle the input size of Cx128x128x128.  Therefore, the network architecture should be modified accordingly to process the input with the size of Cx64x128x128.
