### ISSUE TITLE
RuntimeError when training

### ISSUE THREAD

**Issue by atisman89** [himashi92/VT-UNet#37]
Hi, I followed the installation instruction and started training with following command:
`CUDA_VISIBLE_DEVICES=0 nohup vtunet_train 3d_fullres vtunetTrainerV2_vtunet_tumor 3 0 &> small.out &`

and I get the following error in `small.out` file:
```
...
delete:layers_up.1.blocks.1.mlp.fc2.weight;shape pretrain:torch.Size([21841]);shape model:torch.Size([192, 768])
delete:layers_up.1.blocks.1.mlp.fc2.bias;shape pretrain:torch.Size([21841]);shape model:torch.Size([192])
2023-05-14 20:38:25.769134: lr: 0.0001
/opt/conda/envs/myenv/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Exception in background worker 3:
 mmap length is greater than file size
using pin_memory on device 0
Traceback (most recent call last):
  File "/opt/conda/envs/myenv/bin/vtunet_train", line 33, in <module>
    sys.exit(load_entry_point('vtunet', 'console_scripts', 'vtunet_train')())
  File "/home/VTUNet/vtunet/run/run_training.py", line 150, in main
    trainer.run_training()
  File "/home/VTUNet/vtunet/training/network_training/vtunetTrainerV2_vtunet_tumor.py", line 515, in run_training
    ret = super().run_training()
  File "/home/VTUNet/vtunet/training/network_training/vtunetTrainer.py", line 319, in run_training
    super(vtunetTrainer, self).run_training()
  File "/home/VTUNet/vtunet/training/network_training/network_trainer.py", line 421, in run_training
    _ = self.tr_gen.next()
  File "/opt/conda/envs/myenv/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 181, in next
    return self.__next__()
  File "/opt/conda/envs/myenv/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()
  File "/opt/conda/envs/myenv/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full
```
Any ideas of what could be wrong here?

**Comment by atisman89** [comment]
Resolved by deleting all .npy files under `/home/VTUNet/DATASET/vtunet_preprocessed/Task003_tumor/vtunetData_plans_v2.1_stage0`
According to this thread: https://github.com/MIC-DKFZ/nnUNet/issues/291#issuecomment-674358364
Not sure how I got those files if they should not be there in the first place...
